export const areaOfStudyList = [
  "Aerospace engineering",
  "Agricultural engineering",
  "Architectural engineering",
  "Automotive engineering",
  "Biomechanical engineering",
  "Biomedical engineering",
  "Ceramic engineering",
  "Chemical engineering",
  "Civil engineering",
  "Computer engineering",
  "Computer science",
  "Family and consumer science",
  "Health science",
  "Political science",
  "Systems science",
  "Earth sciences",
  "Life sciences",
  "Military sciences",
  "Space sciences",
  "Mathematics",
  "Chemistry",
  "Business",
  "History",
  "Hardware Design",
  "Interaction Design",
  "Product Design",
  "Visual Design",
  "Psychology",
  "Social work",
  "Sociology",
  "Philosophy",
  "Visual Arts",
  "Performing arts",
  "Education",
  "Language studies",
  "Medicine",
];
