export const jobsData = [
  {
    id: "1",
    title: "60-Minute Testing Job - Android App UI/UX & Bug Testing",
    type: "Hourly",
    rate: "$5",
    level: "Entry level",
    duration: "Est. Time: 1 to 3 months, Less than 30 hrs/week",
    description:
      "Overview: We're looking for testers to help us evaluate a newly published Android app on the Google Play Store. This is an excellent opportunity for those looking to build their Prowork profile with minimal effort. Job Description: You will participate in a simple testing process by downloading the app and logging in daily for a short duration. Your feedback will help us identify any...",
    skills: ["Android", "Mobile App Testing", "Manual Testing"],
    paymentVerified: true,
    rating: 5,
    spent: "$2M+ spent",
    location: "Hong Kong",
    proposals: "50+",
    postedTime: "1 hour ago",
    isSaved: false,
  },
  {
    id: "2",
    title: "Logo Design",
    type: "Fixed-price",
    rate: "$10",
    level: "Expert",
    duration: "Est. Budget: $10",
    description:
      "Need a simple, clean logo created. Will provide brand name and references. Must be open to revisions until satisfied. Fast turnaround required. Budget: $10 Deadline: 1 day NOTE: only apply if ok with deadline and budget",
    skills: ["Logo Design", "Graphic Design"],
    paymentVerified: true,
    rating: 5,
    spent: "$8K+ spent",
    location: "United Kingdom",
    proposals: "20 to 50",
    postedTime: "yesterday",
    isSaved: false,
  },
  {
    id: "3",
    title: "Create Simple Catering Website",
    type: "Fixed-price",
    rate: "$15",
    level: "Intermediate",
    duration: "Est. Budget: $15",
    description:
      "i have recently purchased a domain name and need to create a website for my catering business showcasing our work.",
    skills: ["Website", "Web Design", "Web Development"],
    paymentVerified: true,
    rating: 5,
    spent: "$2K+ spent",
    location: "United Kingdom",
    proposals: "20 to 50",
    postedTime: "yesterday",
    isSaved: false,
  },
  {
    id: "4",
    title: "Easy Daily Data Entry",
    type: "Hourly",
    rate: "$3-$7",
    level: "Entry level",
    duration: "Est. Time: More than 6 months, 30+ hrs/week",
    description:
      "What You'll Be Doing: Copying product info (like names + prices) from websites. Using ChatGPT to clean up or summarise text (we'll show you how) Sending screenshots or a quick task log each day Logging into a shared dashboard (we'll provide login) Takes just 5-10 minutes a day once trained.",
    skills: ["Data Entry", "HTML", "Graphic Design"],
    paymentVerified: true,
    rating: 5,
    spent: "$1K+ spent",
    location: "Australia",
    proposals: "50+",
    postedTime: "2 hours ago",
    isSaved: false,
  },
  {
    id: "5",
    title: "HTML Template Conversion Needed",
    type: "Fixed-price",
    rate: "$5",
    level: "Intermediate",
    duration: "Est. Budget: $5",
    description:
      "We are seeking a skilled freelancer to convert a provided template into simple HTML format, incorporating filler text where necessary. This project involves taking an existing design and translating it into a functional HTML structure that is clean and easy to read.",
    skills: ["HTML", "CSS", "HTML5", "Web Design", "Landing Page"],
    paymentVerified: true,
    rating: 5,
    spent: "$2K+ spent",
    location: "United States",
    proposals: "20 to 50",
    postedTime: "yesterday",
    isSaved: false,
  },
  {
    id: "6",
    title: "Photo & Video Editor | Fast, Creative, and Reliable",
    type: "Hourly",
    rate: "$10-$20",
    level: "Entry level",
    duration: "Est. Time: Less than 1 month, Less than 30 hrs/week",
    description:
      "Hi! My name is Long, and I'm currently working full-time in e-commerce. I'm here on Prowork to find part-time projects after work to earn extra income and do what I enjoy most - editing photos and videos. I have several years of experience working with visual content for online shops and social media.",
    skills: ["Video Editing", "Adobe Photoshop", "Photo Editing"],
    paymentVerified: false,
    spent: "$0 spent",
    location: "Vietnam",
    proposals: "Less than 5",
    postedTime: "8 minutes ago",
    isSaved: false,
  },
];
