name: Deploy to EC2

on:
  push:
    branches: [main, master]
    paths: ['backend/**']

jobs:
  deploy:
    name: Deploy to EC2
    runs-on: ubuntu-latest
    environment: production

    steps:
      - name: SSH into EC2 and git pull
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.EC2_HOST }}
          username: ec2-user
          key: ${{ secrets.EC2_PRIVATE_KEY }}
          script: |
            cd /home/ec2-user/upwork-clone/backend
            git pull origin main
            pnpm install
            pnpm run build
            pm2 restart upwork-backend
