// import type { JobProps } from "@/types/jobs";

// export const mockJobs: JobProps[] = [
//   {
//     id: "1",
//     title: "Video Content Creator",
//     type: "Fixed-price",
//     level: "Intermediate",
//     duration: "Est. budget: $1,000.00",
//     description:
//       "I am looking for a talented video content creator to help me create engaging and high-quality video content for my social media platforms. The ideal candidate should have experience in video editing, motion graphics, and storytelling. We need someone who can create compelling visual narratives that resonate with our target audience and drive engagement across various social media channels.",
//     skills: [
//       "Video Editing",
//       "Motion Graphics",
//       "After Effects",
//       "Premiere Pro",
//     ],
//     paymentVerified: true,
//     rating: 4.8,
//     spent: "$5 spent",
//     location: "United States",
//     proposals: "Less than 5",
//     postedTime: "2 hours ago",
//     rate: "$500",
//   },
//   {
//     id: "2",
//     title: "Freelance Full Stack Developer for Bug Fixes and Website Tweaks",
//     type: "Hourly",
//     level: "Intermediate",
//     duration: "Est. budget: $500.00",
//     description:
//       "Nothing is working a skilled freelance full stack developer to join our team on a project basis. The primary focus will be on addressing bugs and bug fixes, implementing minor website tweaks, and ensuring the overall performance and functionality of both front-end and back-end systems. The ideal candidate should have a solid understanding of both front-end and back-end technologies.",
//     skills: ["Python", "WordPress", "PHP", "JavaScript", "CSS", "HTML"],
//     paymentVerified: true,
//     rating: 4.9,
//     spent: "$5 spent",
//     location: "United States",
//     proposals: "Less than 5",
//     postedTime: "3 hours ago",
//     rate: "$500",
//   },
//   {
//     id: "3",
//     title:
//       "Chrome extension for automation - django backend / front end / api - start now",
//     type: "Hourly",
//     level: "Expert",
//     duration: "Est. budget: $500.00",
//     description:
//       "You will build a chrome extension to automate functions on a website. Many moving URLs, and export CSV results and saving the full info to the database. The extension will be able to work from the chrome browser, access to user fields, and launch the extension. We need someone with experience in browser extension development and API integration.",
//     skills: [
//       "Python",
//       "Google Chrome Extension",
//       "Django",
//       "API",
//       "HTML",
//       "JavaScript",
//       "API Integration",
//     ],
//     paymentVerified: true,
//     rating: 4.7,
//     spent: "$5K+ spent",
//     location: "USA",
//     proposals: "Less than 5",
//     postedTime: "4 hours ago",
//     rate: "$500",
//   },
//   {
//     id: "4",
//     title: "Shopify Developer Needed for E-commerce Customization",
//     type: "Fixed-price",
//     level: "Intermediate",
//     duration: "Est. budget: $800.00",
//     description:
//       "We are looking for an experienced Shopify developer to help customize our e-commerce store. The ideal candidate should be proficient in Shopify theme development, liquid templating, and be able to implement responsive designs. You will work closely with our team to enhance the user experience and optimize the store for conversions.",
//     skills: [
//       "Shopify",
//       "Liquid",
//       "CSS",
//       "JavaScript",
//       "Shopify Templates",
//       "WooCommerce",
//     ],
//     paymentVerified: true,
//     rating: 4.6,
//     spent: "$5K+ spent",
//     location: "Australia",
//     proposals: "5 to 10",
//     postedTime: "5 hours ago",
//     rate: "$500",
//   },
//   {
//     id: "5",
//     title: "Full Stack Engineer Needed for Django and React Project",
//     type: "Hourly",
//     level: "Expert",
//     duration: "Hourly: $40.00 - $80.00",
//     description:
//       "We are seeking a skilled Full Stack Engineer with expertise in Django and React to join our team. The ideal candidate will have experience in building scalable web applications, working with APIs, and collaborating closely with designers and product managers to deliver high-quality solutions. This is a long-term project with potential for ongoing work.",
//     skills: ["Django", "React", "Python", "JavaScript"],
//     paymentVerified: true,
//     rating: 4.8,
//     spent: "$10K+ spent",
//     location: "United States",
//     proposals: "10 to 15",
//     postedTime: "6 hours ago",
//     rate: "$500",
//   },
//   // Adding more jobs for pagination testing
//   {
//     id: "6",
//     title: "Mobile App Developer for iOS and Android",
//     type: "Fixed-price",
//     level: "Expert",
//     duration: "Est. budget: $2,500.00",
//     description:
//       "Looking for an experienced mobile app developer to create a cross-platform application for both iOS and Android. The app should have user authentication, real-time messaging, and payment integration.",
//     skills: ["React Native", "Flutter", "iOS", "Android", "Firebase"],
//     paymentVerified: true,
//     rating: 4.9,
//     spent: "$15K+ spent",
//     location: "Canada",
//     proposals: "5 to 10",
//     postedTime: "1 day ago",
//     rate: "$500",
//   },
//   {
//     id: "7",
//     title: "WordPress Website Redesign",
//     type: "Fixed-price",
//     level: "Intermediate",
//     duration: "Est. budget: $1,200.00",
//     description:
//       "Need to redesign an existing WordPress website with modern design principles, improved user experience, and mobile responsiveness. Must be SEO optimized and fast loading.",
//     skills: ["WordPress", "PHP", "CSS", "JavaScript", "SEO"],
//     paymentVerified: false,
//     rating: 4.5,
//     spent: "$2K+ spent",
//     location: "United Kingdom",
//     proposals: "15 to 20",
//     postedTime: "1 day ago",
//     rate: "$500",
//   },
//   {
//     id: "8",
//     title: "Data Analysis and Visualization Expert",
//     type: "Hourly",
//     level: "Expert",
//     duration: "Hourly: $30.00 - $60.00",
//     description:
//       "Seeking a data analyst to help analyze large datasets and create meaningful visualizations. Experience with Python, R, and data visualization tools required.",
//     skills: ["Python", "R", "Tableau", "Power BI", "SQL"],
//     paymentVerified: true,
//     rating: 4.7,
//     spent: "$8K+ spent",
//     location: "Germany",
//     proposals: "Less than 5",
//     postedTime: "2 days ago",
//     rate: "$500",
//   },
//   {
//     id: "9",
//     title: "UI/UX Designer for SaaS Platform",
//     type: "Fixed-price",
//     level: "Intermediate",
//     duration: "Est. budget: $1,800.00",
//     description:
//       "Looking for a talented UI/UX designer to redesign our SaaS platform interface. Need someone with experience in user research, wireframing, and prototyping.",
//     skills: ["Figma", "Adobe XD", "Sketch", "Prototyping", "User Research"],
//     paymentVerified: true,
//     rating: 4.6,
//     spent: "$3K+ spent",
//     location: "Netherlands",
//     proposals: "10 to 15",
//     postedTime: "2 days ago",
//     rate: "$500",
//   },
//   {
//     id: "10",
//     title: "DevOps Engineer for Cloud Infrastructure",
//     type: "Hourly",
//     level: "Expert",
//     duration: "Hourly: $50.00 - $90.00",
//     description:
//       "Need an experienced DevOps engineer to help set up and maintain cloud infrastructure on AWS. Experience with Docker, Kubernetes, and CI/CD pipelines required.",
//     skills: ["AWS", "Docker", "Kubernetes", "Jenkins", "Terraform"],
//     paymentVerified: true,
//     rating: 4.8,
//     spent: "$20K+ spent",
//     location: "United States",
//     proposals: "Less than 5",
//     postedTime: "3 days ago",
//     rate: "$500",
//   },
//   {
//     id: "11",
//     title: "Content Writer for Tech Blog",
//     type: "Fixed-price",
//     level: "Entry Level",
//     duration: "Est. budget: $300.00",
//     description:
//       "Looking for a content writer to create engaging blog posts about technology trends, software development, and digital marketing. Must have excellent writing skills and tech knowledge.",
//     skills: ["Content Writing", "SEO", "Technical Writing", "Research"],
//     paymentVerified: false,
//     rating: 4.3,
//     spent: "$500+ spent",
//     location: "India",
//     proposals: "20 to 50",
//     postedTime: "3 days ago",
//     rate: "$500",
//   },
//   {
//     id: "12",
//     title: "Machine Learning Engineer for AI Project",
//     type: "Hourly",
//     level: "Expert",
//     duration: "Hourly: $60.00 - $100.00",
//     description:
//       "Seeking an experienced ML engineer to develop and deploy machine learning models for our AI-powered application. Experience with TensorFlow, PyTorch, and cloud deployment required.",
//     skills: ["Python", "TensorFlow", "PyTorch", "Machine Learning", "AI"],
//     paymentVerified: true,
//     rating: 4.9,
//     spent: "$25K+ spent",
//     location: "United States",
//     proposals: "Less than 5",
//     postedTime: "4 days ago",
//     rate: "$500",
//   },
// ];
